// Automatically generated wrapper file 
// Generated by scripts/build_jswrapper.py

#include "jswrapper.h"
#include "jsnative.h"
#include "jswrap_array.h"
#include "jswrap_arraybuffer.h"
#include "jswrap_date.h"
#include "jswrap_error.h"
#include "jswrap_espruino.h"
#include "jswrap_functions.h"
#include "jswrap_interactive.h"
#include "jswrap_io.h"
#include "jswrap_json.h"
#include "jswrap_modules.h"
#include "jswrap_number.h"
#include "jswrap_object.h"
#include "jswrap_onewire.h"
#include "jswrap_pin.h"
#include "jswrap_pipe.h"
#include "jswrap_process.h"
#include "jswrap_serial.h"
#include "jswrap_spi_i2c.h"
#include "jswrap_stream.h"
#include "jswrap_string.h"
#include "jswrap_waveform.h"
#include "jswrap_math.h"
#include "jspininfo.h"


// -----------------------------------------------------------------------------------------
// ----------------------------------------------------------------- AUTO-GENERATED WRAPPERS
// -----------------------------------------------------------------------------------------

static JsVar* gen_jswrap_Array_pop(JsVar *parent) {
  return jsvArrayPop(parent);
}

static bool gen_jswrap_Array_isArray(JsVar* var) {
  return jsvIsArray(var);
}

static JsVar* gen_jswrap_Uint8Array_Uint8Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_UINT8, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Uint8ClampedArray_Uint8ClampedArray(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_UINT8|ARRAYBUFFERVIEW_CLAMPED, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Int8Array_Int8Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_INT8, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Uint16Array_Uint16Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_UINT16, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Int16Array_Int16Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_INT16, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Uint32Array_Uint32Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_UINT32, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Int32Array_Int32Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_INT32, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Float32Array_Float32Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_FLOAT32, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Float64Array_Float64Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_FLOAT64, arr, byteOffset, length);
}

static JsVar* gen_jswrap_ArrayBufferView_buffer(JsVar *parent) {
  return jsvLock(jsvGetFirstChild(parent));
}

static JsVarInt gen_jswrap_ArrayBufferView_byteLength(JsVar *parent) {
  return (JsVarInt)(parent->varData.arraybuffer.length * JSV_ARRAYBUFFER_GET_SIZE(parent->varData.arraybuffer.type));
}

static JsVarInt gen_jswrap_ArrayBufferView_byteOffset(JsVar *parent) {
  return parent->varData.arraybuffer.byteOffset;
}

static JsVarFloat gen_jswrap_E_getTemperature() {
  return jshReadTemperature();
}

static JsVarFloat gen_jswrap_E_getAnalogVRef() {
  return jshReadVRef();
}

static void gen_jswrap_load() {
  jsiSetTodo(TODO_FLASH_LOAD);
}

static void gen_jswrap_save() {
  jsiSetTodo(TODO_FLASH_SAVE);
}

static void gen_jswrap_reset() {
  jsiSetTodo(TODO_RESET);
}

static JsVarFloat gen_jswrap_getTime() {
  return (JsVarFloat)jshGetSystemTime() / (JsVarFloat)jshGetTimeFromMilliseconds(1000);
}

static JsVar* gen_jswrap_peek8(JsVarInt addr, JsVarInt count) {
  return jswrap_io_peek(addr,count,1);
}

static void gen_jswrap_poke8(JsVarInt addr, JsVar* value) {
  jswrap_io_poke(addr,value,1);
}

static JsVar* gen_jswrap_peek16(JsVarInt addr, JsVarInt count) {
  return jswrap_io_peek(addr,count,2);
}

static void gen_jswrap_poke16(JsVarInt addr, JsVar* value) {
  jswrap_io_poke(addr,value,2);
}

static JsVar* gen_jswrap_peek32(JsVarInt addr, JsVarInt count) {
  return jswrap_io_peek(addr,count,4);
}

static void gen_jswrap_poke32(JsVarInt addr, JsVar* value) {
  jswrap_io_poke(addr,value,4);
}

static JsVarFloat gen_jswrap_NaN() {
  return NAN;
}

static JsVarFloat gen_jswrap_Infinity() {
  return INFINITY;
}

static JsVarFloat gen_jswrap_Number_NaN() {
  return NAN;
}

static JsVarFloat gen_jswrap_Number_MAX_VALUE() {
  return DBL_MAX;
}

static JsVarFloat gen_jswrap_Number_MIN_VALUE() {
  return DBL_MIN;
}

static JsVarFloat gen_jswrap_Number_NEGATIVE_INFINITY() {
  return -INFINITY;
}

static JsVarFloat gen_jswrap_Number_POSITIVE_INFINITY() {
  return INFINITY;
}

static int gen_jswrap_HIGH() {
  return 1;
}

static int gen_jswrap_LOW() {
  return 0;
}

static JsVar* gen_jswrap_Object_keys(JsVar* object) {
  return jswrap_object_keys_or_property_names(object, false);
}

static JsVar* gen_jswrap_Object_getOwnPropertyNames(JsVar* object) {
  return jswrap_object_keys_or_property_names(object, true);
}

static JsVar* gen_jswrap_process_version() {
  return jsvNewFromString(JS_VERSION);
}

static JsVar* gen_jswrap_Serial1() {
  return jspNewObject("Serial1", "Serial") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
}

static JsVar* gen_jswrap_Serial2() {
  return jspNewObject("Serial2", "Serial") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
}

static JsVar* gen_jswrap_Serial3() {
  return jspNewObject("Serial3", "Serial") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
}

static JsVar* gen_jswrap_LoopbackA() {
  return jspNewObject("LoopbackA", "Serial") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
}

static JsVar* gen_jswrap_LoopbackB() {
  return jspNewObject("LoopbackB", "Serial") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
}

static void gen_jswrap_Serial_setConsole(JsVar *parent) {
  jsiSetConsoleDevice(jsiGetDeviceFromClass(parent));
}

static JsVar* gen_jswrap_SPI1() {
  return jspNewObject("SPI1", "SPI") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
}

static JsVar* gen_jswrap_SPI2() {
  return jspNewObject("SPI2", "SPI") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
}

static JsVar* gen_jswrap_SPI3() {
  return jspNewObject("SPI3", "SPI") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
}

static JsVar* gen_jswrap_I2C1() {
  return jspNewObject("I2C1", "I2C") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
}

static JsVar* gen_jswrap_I2C2() {
  return jspNewObject("I2C2", "I2C") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
}

static JsVar* gen_jswrap_I2C3() {
  return jspNewObject("I2C3", "I2C") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
}

static int gen_jswrap_String_indexOf(JsVar *parent, JsVar* substring, JsVar* fromIndex) {
  return jswrap_string_indexOf(parent, substring, fromIndex, false);
}

static int gen_jswrap_String_lastIndexOf(JsVar *parent, JsVar* substring, JsVar* fromIndex) {
  return jswrap_string_indexOf(parent, substring, fromIndex, true);
}

static JsVar* gen_jswrap_String_toLowerCase(JsVar *parent) {
  return jswrap_string_toUpperLowerCase(parent, false);
}

static JsVar* gen_jswrap_String_toUpperCase(JsVar *parent) {
  return jswrap_string_toUpperLowerCase(parent, true);
}

static JsVarFloat gen_jswrap_Math_E() {
  return 2.718281828459045;
}

static JsVarFloat gen_jswrap_Math_PI() {
  return PI;
}

static JsVarFloat gen_jswrap_Math_LN2() {
  return 0.6931471805599453;
}

static JsVarFloat gen_jswrap_Math_LN10() {
  return 2.302585092994046;
}

static JsVarFloat gen_jswrap_Math_LOG2E() {
  return 1.4426950408889634;
}

static JsVarFloat gen_jswrap_Math_LOG10E() {
  return 0.4342944819032518;
}

static JsVarFloat gen_jswrap_Math_SQRT2() {
  return 1.4142135623730951;
}

static JsVarFloat gen_jswrap_Math_SQRT1_2() {
  return 0.7071067811865476;
}

static JsVarFloat gen_jswrap_Math_cos(JsVarFloat theta) {
  return sin(theta + (PI/2));
}

static JsVarFloat gen_jswrap_Math_random() {
  return (JsVarFloat)rand() / (JsVarFloat)RAND_MAX;
}

static JsVarFloat gen_jswrap_Math_tan(JsVarFloat theta) {
  return sin(theta) / sin(theta+(PI/2));
}

static JsVarFloat gen_jswrap_Math_min(JsVar* args) {
  return jswrap_math_minmax(args, false);
}

static JsVarFloat gen_jswrap_Math_max(JsVar* args) {
  return jswrap_math_minmax(args, true);
}

static JsVarInt gen_jswrap_Graphics_getWidth(JsVar *parent) {
  //return jswrap_graphics_getWidthOrHeight(parent, false);
}

static JsVarInt gen_jswrap_Graphics_getHeight(JsVar *parent) {
  //return jswrap_graphics_getWidthOrHeight(parent, true);
}

static void gen_jswrap_Graphics_setColor(JsVar *parent, JsVar* r, JsVar* g, JsVar* b) {
  //jswrap_graphics_setColorX(parent, r,g,b, true, false);
}

static void gen_jswrap_Graphics_setBgColor(JsVar *parent, JsVar* r, JsVar* g, JsVar* b) {
  //jswrap_graphics_setColorX(parent, r,g,b, false, false);
}

static void gen_jswrap_Graphics_setColorHSV(JsVar *parent, JsVar* h, JsVar* s, JsVar* v) {
  //jswrap_graphics_setColorX(parent, h,s,v, true, true);
}

static void gen_jswrap_Graphics_setBgColorHSV(JsVar *parent, JsVar* h, JsVar* s, JsVar* v) {
  //jswrap_graphics_setColorX(parent, h,s,v, false, true);
}

static JsVarInt gen_jswrap_Graphics_getColor(JsVar *parent) {
  //return jswrap_graphics_getColorX(parent, true);
}

static JsVarInt gen_jswrap_Graphics_getBgColor(JsVar *parent) {
  //return jswrap_graphics_getColorX(parent, false);
}

static void gen_jswrap_Graphics_setFontBitmap(JsVar *parent) {
  //jswrap_graphics_setFontSizeX(parent, JSGRAPHICS_FONTSIZE_4X6, false);
}

static void gen_jswrap_Graphics_setFontVector(JsVar *parent, int size) {
  //jswrap_graphics_setFontSizeX(parent, size, true);
}

static JsVar* gen_jswrap_net_connect(JsVar* options, JsVar* callback) {
  //return jswrap_net_connect(options, callback, ST_NORMAL);
	return 0;
}

static JsVar* gen_jswrap_http_request(JsVar* options, JsVar* callback) {
  //return jswrap_net_connect(options, callback, ST_HTTP);
	return 0;
}

static JsVar* gen_jswrap_ArrayBufferView_ArrayBufferView() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_E_E() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_console_console() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_JSON_JSON() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Modules_Modules() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Hardware_Hardware() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Object_Object() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Pipe_Pipe() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_fs_fs() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_process_process() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Serial_Serial() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_I2C_I2C() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Math_Math() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Graphics_Graphics() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_url_url() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_net_net() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Server_Server() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Socket_Socket() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_http_http() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_httpSrv_httpSrv() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_httpSRq_httpSRq() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_httpSRs_httpSRs() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_httpCRq_httpCRq() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_httpCRs_httpCRs() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_CC3000_CC3000() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_WLAN_WLAN() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Nucleo_Nucleo() {
  return jsvNewWithFlags(JSV_OBJECT);
}

// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------


JsVar *jswBinarySearch(const JswSymList *symbolsPtr, JsVar *parent, const char *name) {
  int searchMin = 0;
  int searchMax = symbolsPtr->symbolCount-1;
  while (searchMin <= searchMax) {
    int idx = (searchMin+searchMax) >> 1;
    const JswSymPtr *sym = &symbolsPtr->symbols[idx];
    int cmp = strcmp(name, &symbolsPtr->symbolChars[sym->strOffset]);
    if (cmp==0) {
      if ((sym->functionSpec & JSWAT_EXECUTE_IMMEDIATELY_MASK) == JSWAT_EXECUTE_IMMEDIATELY)
        return jsnCallFunction(sym->functionPtr, sym->functionSpec, parent, 0, 0);
      return jsvNewNativeFunction(sym->functionPtr, sym->functionSpec);
    } else {
      if (cmp<0) {
        // searchMin is the same
        searchMax = idx-1;
      } else { 
        searchMin = idx+1;
        // searchMax is the same      
      }
    }
  }
  return 0;
}

// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------


static const JswSymPtr jswSymbols_I2C_proto[] = {
  {0, (void (*)(void))jswrap_i2c_readFrom, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2))},
  {9, (void (*)(void))jswrap_i2c_setup, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {15, (void (*)(void))jswrap_i2c_writeTo, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*2))}
};
static const unsigned char jswSymbolIndex_I2C_proto = 0;
static const JswSymPtr jswSymbols_Date_proto[] = {
  {0, (void (*)(void))jswrap_date_getDate, JSWAT_INT32 | JSWAT_THIS_ARG},
  {8, (void (*)(void))jswrap_date_getDay, JSWAT_INT32 | JSWAT_THIS_ARG},
  {15, (void (*)(void))jswrap_date_getFullYear, JSWAT_INT32 | JSWAT_THIS_ARG},
  {27, (void (*)(void))jswrap_date_getHours, JSWAT_INT32 | JSWAT_THIS_ARG},
  {36, (void (*)(void))jswrap_date_getMilliseconds, JSWAT_INT32 | JSWAT_THIS_ARG},
  {52, (void (*)(void))jswrap_date_getMinutes, JSWAT_INT32 | JSWAT_THIS_ARG},
  {63, (void (*)(void))jswrap_date_getMonth, JSWAT_INT32 | JSWAT_THIS_ARG},
  {72, (void (*)(void))jswrap_date_getSeconds, JSWAT_INT32 | JSWAT_THIS_ARG},
  {83, (void (*)(void))jswrap_date_getTime, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG},
  {91, (void (*)(void))jswrap_date_getTimezoneOffset, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG},
  {109, (void (*)(void))jswrap_date_toString, JSWAT_JSVAR | JSWAT_THIS_ARG},
  {118, (void (*)(void))jswrap_date_toUTCString, JSWAT_JSVAR | JSWAT_THIS_ARG},
  {130, (void (*)(void))jswrap_date_getTime, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG}
};
static const unsigned char jswSymbolIndex_Date_proto = 1;
static const JswSymPtr jswSymbols_Graphics[] = {
  //{0, (void (*)(void))jswrap_graphics_createArrayBuffer, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)) | (JSWAT_JSVAR << (JSWAT_BITS*4))},
  //{18, (void (*)(void))jswrap_graphics_createCallback, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)) | (JSWAT_JSVAR << (JSWAT_BITS*4))}
};
static const unsigned char jswSymbolIndex_Graphics = 2;
static const JswSymPtr jswSymbols_E[] = {
  {0, (void (*)(void))jswrap_espruino_FFT, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3))},
  {4, (void (*)(void))jswrap_espruino_clip, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*3))},
  {9, (void (*)(void))jswrap_espruino_convolve, JSWAT_JSVARFLOAT | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3))},
  {18, (void (*)(void))jswrap_espruino_dumpTimers, JSWAT_VOID},
  {29, (void (*)(void))jswrap_espruino_enableWatchdog, JSWAT_VOID | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {44, (void (*)(void))gen_jswrap_E_getAnalogVRef, JSWAT_JSVARFLOAT},
  {58, (void (*)(void))jswrap_espruino_getErrorFlags, JSWAT_JSVAR},
  {72, (void (*)(void))jswrap_espruino_getSizeOf, JSWAT_INT32 | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {82, (void (*)(void))gen_jswrap_E_getTemperature, JSWAT_JSVARFLOAT},
  {97, (void (*)(void))jswrap_espruino_interpolate, JSWAT_JSVARFLOAT | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2))},
  {109, (void (*)(void))jswrap_espruino_interpolate2d, JSWAT_JSVARFLOAT | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*3)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*4))},
  {123, (void (*)(void))jswrap_espruino_nativeCall, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {134, (void (*)(void))jswrap_espruino_reverseByte, JSWAT_INT32 | (JSWAT_INT32 << (JSWAT_BITS*1))},
  {146, (void (*)(void))jswrap_espruino_sum, JSWAT_JSVARFLOAT | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {150, (void (*)(void))jswrap_espruino_toArrayBuffer, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {164, (void (*)(void))jswrap_espruino_toString, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))},
  {173, (void (*)(void))jswrap_espruino_toUint8Array, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))},
  {186, (void (*)(void))jswrap_espruino_variance, JSWAT_JSVARFLOAT | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2))}
};
static const unsigned char jswSymbolIndex_E = 3;
static const JswSymPtr jswSymbols_Server_proto[] = {
  //{0, (void (*)(void))jswrap_net_server_close, JSWAT_VOID | JSWAT_THIS_ARG},
  //{6, (void (*)(void))jswrap_net_server_listen, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_Server_proto = 4;
static const JswSymPtr jswSymbols_Socket[] = {
  
};
static const unsigned char jswSymbolIndex_Socket = 5;
static const JswSymPtr jswSymbols_String_proto[] = {
  {0, (void (*)(void))jswrap_string_charAt, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1))},
  {7, (void (*)(void))jswrap_string_charCodeAt, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1))},
  {18, (void (*)(void))gen_jswrap_String_indexOf, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {26, (void (*)(void))gen_jswrap_String_lastIndexOf, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {38, (void (*)(void))jswrap_object_length, JSWAT_JSVAR | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY},
  {45, (void (*)(void))jswrap_string_replace, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {53, (void (*)(void))jswrap_string_slice, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {59, (void (*)(void))jswrap_string_split, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {65, (void (*)(void))jswrap_string_substr, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {72, (void (*)(void))jswrap_string_substring, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {82, (void (*)(void))gen_jswrap_String_toLowerCase, JSWAT_JSVAR | JSWAT_THIS_ARG},
  {94, (void (*)(void))gen_jswrap_String_toUpperCase, JSWAT_JSVAR | JSWAT_THIS_ARG}
};
static const unsigned char jswSymbolIndex_String_proto = 6;
static const JswSymPtr jswSymbols_OneWire_proto[] = {
  {0, (void (*)(void))jswrap_onewire_read, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {5, (void (*)(void))jswrap_onewire_reset, JSWAT_BOOL | JSWAT_THIS_ARG},
  {11, (void (*)(void))jswrap_onewire_search, JSWAT_JSVAR | JSWAT_THIS_ARG},
  {18, (void (*)(void))jswrap_onewire_search, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1))},
  {25, (void (*)(void))jswrap_onewire_select, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {32, (void (*)(void))jswrap_onewire_skip, JSWAT_VOID | JSWAT_THIS_ARG},
  {37, (void (*)(void))jswrap_onewire_write, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2))}
};
static const unsigned char jswSymbolIndex_OneWire_proto = 7;
static const JswSymPtr jswSymbols_Serial[] = {
  
};
static const unsigned char jswSymbolIndex_Serial = 8;
static const JswSymPtr jswSymbols_httpSRs_proto[] = {
  //{0, (void (*)(void))jswrap_httpSRs_end, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  //{4, (void (*)(void))jswrap_httpSRs_write, JSWAT_BOOL | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  //{10, (void (*)(void))jswrap_httpSRs_writeHead, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))}
};
static const unsigned char jswSymbolIndex_httpSRs_proto = 9;
static const JswSymPtr jswSymbols_JSON[] = {
  {0, (void (*)(void))jswrap_json_parse, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {6, (void (*)(void))jswrap_json_stringify, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_JSON = 10;
static const JswSymPtr jswSymbols_global[] = {
  {0, (void (*)(void))jswrap_array_constructor, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))},
  {6, (void (*)(void))jswrap_arraybuffer_constructor, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1))},
  {18, (void (*)(void))gen_jswrap_ArrayBufferView_ArrayBufferView, JSWAT_JSVAR},
  {34, (void (*)(void))jswrap_boolean_constructor, JSWAT_BOOL | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {42, (void (*)(void))jswrap_date_constructor, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))},
  {47, (void (*)(void))gen_jswrap_E_E, JSWAT_JSVAR},
  {49, (void (*)(void))jswrap_error_constructor, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {55, (void (*)(void))gen_jswrap_Float32Array_Float32Array, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3))},
  {68, (void (*)(void))gen_jswrap_Float64Array_Float64Array, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3))},
  {81, (void (*)(void))jswrap_function_constructor, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {90, (void (*)(void))gen_jswrap_Graphics_Graphics, JSWAT_JSVAR},
  {99, (void (*)(void))gen_jswrap_HIGH, JSWAT_INT32 | JSWAT_EXECUTE_IMMEDIATELY},
  {104, (void (*)(void))gen_jswrap_Hardware_Hardware, JSWAT_JSVAR},
  {113, (void (*)(void))gen_jswrap_I2C_I2C, JSWAT_JSVAR},
  {117, (void (*)(void))gen_jswrap_I2C1, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY},
  {122, (void (*)(void))gen_jswrap_I2C2, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY},
  {127, (void (*)(void))gen_jswrap_I2C3, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY},
  {132, (void (*)(void))gen_jswrap_Infinity, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {141, (void (*)(void))gen_jswrap_Int16Array_Int16Array, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3))},
  {152, (void (*)(void))gen_jswrap_Int32Array_Int32Array, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3))},
  {163, (void (*)(void))gen_jswrap_Int8Array_Int8Array, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3))},
  {173, (void (*)(void))jswrap_internalerror_constructor, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {187, (void (*)(void))gen_jswrap_JSON_JSON, JSWAT_JSVAR},
  {192, (void (*)(void))gen_jswrap_LOW, JSWAT_INT32 | JSWAT_EXECUTE_IMMEDIATELY},
  {196, (void (*)(void))gen_jswrap_LoopbackA, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY},
  {206, (void (*)(void))gen_jswrap_LoopbackB, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY},
  {216, (void (*)(void))gen_jswrap_Math_Math, JSWAT_JSVAR},
  {221, (void (*)(void))gen_jswrap_Modules_Modules, JSWAT_JSVAR},
  {229, (void (*)(void))gen_jswrap_NaN, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {233, (void (*)(void))gen_jswrap_Nucleo_Nucleo, JSWAT_JSVAR},
  {240, (void (*)(void))jswrap_number_constructor, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))},
  {247, (void (*)(void))gen_jswrap_Object_Object, JSWAT_JSVAR},
  {254, (void (*)(void))jswrap_onewire_constructor, JSWAT_JSVAR | (JSWAT_PIN << (JSWAT_BITS*1))},
  {262, (void (*)(void))jswrap_pin_constructor, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {266, (void (*)(void))jswrap_spi_constructor, JSWAT_VOID},
  {270, (void (*)(void))gen_jswrap_SPI1, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY},
  {275, (void (*)(void))gen_jswrap_SPI2, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY},
  {280, (void (*)(void))gen_jswrap_SPI3, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY},
  {285, (void (*)(void))gen_jswrap_Serial_Serial, JSWAT_JSVAR},
  {292, (void (*)(void))gen_jswrap_Serial1, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY},
  {300, (void (*)(void))gen_jswrap_Serial2, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY},
  {308, (void (*)(void))gen_jswrap_Serial3, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY},
  {316, (void (*)(void))gen_jswrap_Server_Server, JSWAT_JSVAR},
  {323, (void (*)(void))gen_jswrap_Socket_Socket, JSWAT_JSVAR},
  {330, (void (*)(void))jswrap_string_constructor, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))},
  {337, (void (*)(void))jswrap_syntaxerror_constructor, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {349, (void (*)(void))gen_jswrap_Uint16Array_Uint16Array, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3))},
  {361, (void (*)(void))gen_jswrap_Uint32Array_Uint32Array, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3))},
  {373, (void (*)(void))gen_jswrap_Uint8Array_Uint8Array, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3))},
  {384, (void (*)(void))gen_jswrap_Uint8ClampedArray_Uint8ClampedArray, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3))},
  {402, (void (*)(void))gen_jswrap_WLAN_WLAN, JSWAT_JSVAR},
  {407, (void (*)(void))jswrap_waveform_constructor, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {416, (void (*)(void))jshPinAnalog, JSWAT_JSVARFLOAT | (JSWAT_PIN << (JSWAT_BITS*1))},
  {427, (void (*)(void))jswrap_io_analogWrite, JSWAT_VOID | (JSWAT_PIN << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {439, (void (*)(void))jswrap_arguments, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY},
  {449, (void (*)(void))jswrap_atob, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {454, (void (*)(void))jswrap_btoa, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {459, (void (*)(void))jswrap_interface_changeInterval, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2))},
  {474, (void (*)(void))jswrap_interface_clearInterval, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {488, (void (*)(void))jswrap_interface_clearTimeout, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {501, (void (*)(void))jswrap_interface_clearWatch, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {512, (void (*)(void))gen_jswrap_console_console, JSWAT_JSVAR},
  {520, (void (*)(void))jswrap_io_digitalPulse, JSWAT_VOID | (JSWAT_PIN << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {533, (void (*)(void))jswrap_io_digitalRead, JSWAT_INT32 | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {545, (void (*)(void))jswrap_io_digitalWrite, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2))},
  {558, (void (*)(void))jsiDumpState, JSWAT_VOID},
  {563, (void (*)(void))jswrap_interface_echo, JSWAT_VOID | (JSWAT_BOOL << (JSWAT_BITS*1))},
  {568, (void (*)(void))jswrap_interface_edit, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {573, (void (*)(void))jswrap_eval, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {578, (void (*)(void))gen_jswrap_fs_fs, JSWAT_JSVAR},
  {581, (void (*)(void))jswrap_io_getPinMode, JSWAT_JSVAR | (JSWAT_PIN << (JSWAT_BITS*1))},
  {592, (void (*)(void))jswrap_interface_getSerial, JSWAT_JSVAR},
  {602, (void (*)(void))gen_jswrap_getTime, JSWAT_JSVARFLOAT},
  {610, (void (*)(void))gen_jswrap_httpCRq_httpCRq, JSWAT_JSVAR},
  {618, (void (*)(void))gen_jswrap_httpCRs_httpCRs, JSWAT_JSVAR},
  {626, (void (*)(void))gen_jswrap_httpSRq_httpSRq, JSWAT_JSVAR},
  {634, (void (*)(void))gen_jswrap_httpSRs_httpSRs, JSWAT_JSVAR},
  {642, (void (*)(void))gen_jswrap_httpSrv_httpSrv, JSWAT_JSVAR},
  {650, (void (*)(void))jswrap_isNaN, JSWAT_BOOL | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {656, (void (*)(void))gen_jswrap_load, JSWAT_VOID},
  {661, (void (*)(void))jswrap_parseFloat, JSWAT_JSVARFLOAT | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {672, (void (*)(void))jswrap_parseInt, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {681, (void (*)(void))gen_jswrap_peek16, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2))},
  {688, (void (*)(void))gen_jswrap_peek32, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2))},
  {695, (void (*)(void))gen_jswrap_peek8, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2))},
  {701, (void (*)(void))jswrap_io_pinMode, JSWAT_VOID | (JSWAT_PIN << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {709, (void (*)(void))gen_jswrap_poke16, JSWAT_VOID | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {716, (void (*)(void))gen_jswrap_poke32, JSWAT_VOID | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {723, (void (*)(void))gen_jswrap_poke8, JSWAT_VOID | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {729, (void (*)(void))jswrap_interface_print, JSWAT_VOID | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))},
  {735, (void (*)(void))gen_jswrap_process_process, JSWAT_JSVAR},
  {743, (void (*)(void))jswrap_require, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {751, (void (*)(void))gen_jswrap_reset, JSWAT_VOID},
  {757, (void (*)(void))gen_jswrap_save, JSWAT_VOID},
  {762, (void (*)(void))jswrap_interface_setBusyIndicator, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {779, (void (*)(void))jswrap_interface_setDeepSleep, JSWAT_VOID | (JSWAT_BOOL << (JSWAT_BITS*1))},
  {792, (void (*)(void))jswrap_interface_setInterval, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2))},
  {804, (void (*)(void))jswrap_interface_setSleepIndicator, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {822, (void (*)(void))jswrap_interactive_setTime, JSWAT_VOID | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {830, (void (*)(void))jswrap_interface_setTimeout, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2))},
  {841, (void (*)(void))jswrap_interface_setWatch, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_PIN << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {850, (void (*)(void))jswrap_interface_trace, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {856, (void (*)(void))gen_jswrap_url_url, JSWAT_JSVAR}
};
static const unsigned char jswSymbolIndex_global = 11;
static const JswSymPtr jswSymbols_Modules[] = {
  {0, (void (*)(void))jswrap_modules_addCached, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {10, (void (*)(void))jswrap_modules_getCached, JSWAT_JSVAR},
  {20, (void (*)(void))jswrap_modules_removeAllCached, JSWAT_VOID},
  {36, (void (*)(void))jswrap_modules_removeCached, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_Modules = 12;
static const JswSymPtr jswSymbols_Error_proto[] = {
  {0, (void (*)(void))jswrap_error_toString, JSWAT_JSVAR | JSWAT_THIS_ARG}
};
static const unsigned char jswSymbolIndex_Error_proto = 13;
static const JswSymPtr jswSymbols_Object[] = {
  {0, (void (*)(void))jswrap_object_create, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {7, (void (*)(void))jswrap_object_getOwnPropertyDescriptor, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {32, (void (*)(void))gen_jswrap_Object_getOwnPropertyNames, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {52, (void (*)(void))gen_jswrap_Object_keys, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_Object = 14;
static const JswSymPtr jswSymbols_httpCRq[] = {
  
};
static const unsigned char jswSymbolIndex_httpCRq = 15;
static const JswSymPtr jswSymbols_Serial_proto[] = {
  {0, (void (*)(void))jswrap_stream_available, JSWAT_INT32 | JSWAT_THIS_ARG},
  {10, (void (*)(void))jswrap_serial_onData, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {17, (void (*)(void))jswrap_pipe, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {22, (void (*)(void))jswrap_serial_print, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {28, (void (*)(void))jswrap_serial_println, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {36, (void (*)(void))jswrap_stream_read, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1))},
  {41, (void (*)(void))gen_jswrap_Serial_setConsole, JSWAT_VOID | JSWAT_THIS_ARG},
  {52, (void (*)(void))jswrap_serial_setup, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {58, (void (*)(void))jswrap_serial_write, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_Serial_proto = 16;
static const JswSymPtr jswSymbols_CC3000[] = {
  //{0, (void (*)(void))jswrap_cc3000_connect, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_PIN << (JSWAT_BITS*2)) | (JSWAT_PIN << (JSWAT_BITS*3)) | (JSWAT_PIN << (JSWAT_BITS*4))}
};
static const unsigned char jswSymbolIndex_CC3000 = 17;
static const JswSymPtr jswSymbols_Array[] = {
  {0, (void (*)(void))gen_jswrap_Array_isArray, JSWAT_BOOL | (JSWAT_JSVAR << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_Array = 18;
static const JswSymPtr jswSymbols_Number[] = {
  {0, (void (*)(void))gen_jswrap_Number_MAX_VALUE, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {10, (void (*)(void))gen_jswrap_Number_MIN_VALUE, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {20, (void (*)(void))gen_jswrap_Number_NEGATIVE_INFINITY, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {38, (void (*)(void))gen_jswrap_Number_NaN, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {42, (void (*)(void))gen_jswrap_Number_POSITIVE_INFINITY, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY}
};
static const unsigned char jswSymbolIndex_Number = 19;
static const JswSymPtr jswSymbols_Math[] = {
  {0, (void (*)(void))gen_jswrap_Math_E, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {2, (void (*)(void))gen_jswrap_Math_LN10, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {7, (void (*)(void))gen_jswrap_Math_LN2, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {11, (void (*)(void))gen_jswrap_Math_LOG10E, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {18, (void (*)(void))gen_jswrap_Math_LOG2E, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {24, (void (*)(void))gen_jswrap_Math_PI, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {27, (void (*)(void))gen_jswrap_Math_SQRT1_2, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {35, (void (*)(void))gen_jswrap_Math_SQRT2, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY},
  {41, (void (*)(void))jswrap_math_abs, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {45, (void (*)(void))acos, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {50, (void (*)(void))asin, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {55, (void (*)(void))atan, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {60, (void (*)(void))atan2, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2))},
  {66, (void (*)(void))ceil, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {71, (void (*)(void))jswrap_math_clip, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*3))},
  {76, (void (*)(void))gen_jswrap_Math_cos, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {80, (void (*)(void))exp, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {84, (void (*)(void))floor, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {90, (void (*)(void))log, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {94, (void (*)(void))gen_jswrap_Math_max, JSWAT_JSVARFLOAT | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))},
  {98, (void (*)(void))gen_jswrap_Math_min, JSWAT_JSVARFLOAT | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))},
  {102, (void (*)(void))jswrap_math_pow, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2))},
  {106, (void (*)(void))gen_jswrap_Math_random, JSWAT_JSVARFLOAT},
  {113, (void (*)(void))jswrap_math_round, JSWAT_JSVAR | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {119, (void (*)(void))sin, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {123, (void (*)(void))jswrap_math_sqrt, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {128, (void (*)(void))gen_jswrap_Math_tan, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1))},
  {132, (void (*)(void))wrapAround, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2))}
};
static const unsigned char jswSymbolIndex_Math = 20;
static const JswSymPtr jswSymbols_Graphics_proto[] = {
		/*
  {0, (void (*)(void))jswrap_graphics_clear, JSWAT_VOID | JSWAT_THIS_ARG},
  {6, (void (*)(void))jswrap_graphics_drawImage, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3))},
  {16, (void (*)(void))jswrap_graphics_drawLine, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)) | (JSWAT_INT32 << (JSWAT_BITS*4))},
  {25, (void (*)(void))jswrap_graphics_drawRect, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)) | (JSWAT_INT32 << (JSWAT_BITS*4))},
  {34, (void (*)(void))jswrap_graphics_drawString, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3))},
  {45, (void (*)(void))jswrap_graphics_fillPoly, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {54, (void (*)(void))jswrap_graphics_fillRect, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)) | (JSWAT_INT32 << (JSWAT_BITS*4))},
  {63, (void (*)(void))gen_jswrap_Graphics_getBgColor, JSWAT_INT32 | JSWAT_THIS_ARG},
  {74, (void (*)(void))gen_jswrap_Graphics_getColor, JSWAT_INT32 | JSWAT_THIS_ARG},
  {83, (void (*)(void))gen_jswrap_Graphics_getHeight, JSWAT_INT32 | JSWAT_THIS_ARG},
  {93, (void (*)(void))jswrap_graphics_getPixel, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2))},
  {102, (void (*)(void))gen_jswrap_Graphics_getWidth, JSWAT_INT32 | JSWAT_THIS_ARG},
  {111, (void (*)(void))jswrap_graphics_lineTo, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2))},
  {118, (void (*)(void))jswrap_graphics_moveTo, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2))},
  {125, (void (*)(void))gen_jswrap_Graphics_setBgColor, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {136, (void (*)(void))gen_jswrap_Graphics_setBgColorHSV, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {150, (void (*)(void))gen_jswrap_Graphics_setColor, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {159, (void (*)(void))gen_jswrap_Graphics_setColorHSV, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {171, (void (*)(void))gen_jswrap_Graphics_setFontBitmap, JSWAT_VOID | JSWAT_THIS_ARG},
  {185, (void (*)(void))jswrap_graphics_setFontCustom, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)) | (JSWAT_INT32 << (JSWAT_BITS*4))},
  {199, (void (*)(void))gen_jswrap_Graphics_setFontVector, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1))},
  {213, (void (*)(void))jswrap_graphics_setPixel, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {222, (void (*)(void))jswrap_graphics_setRotation, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2))},
  {234, (void (*)(void))jswrap_graphics_stringWidth, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))}
*/
};
static const unsigned char jswSymbolIndex_Graphics_proto = 21;
static const JswSymPtr jswSymbols_fs[] = {
  {0, (void (*)(void))jswrap_pipe, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))}
};
static const unsigned char jswSymbolIndex_fs = 22;
static const JswSymPtr jswSymbols_InternalError_proto[] = {
  {0, (void (*)(void))jswrap_error_toString, JSWAT_JSVAR | JSWAT_THIS_ARG}
};
static const unsigned char jswSymbolIndex_InternalError_proto = 23;
static const JswSymPtr jswSymbols_http[] = {
  //{0, (void (*)(void))jswrap_http_createServer, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  //{13, (void (*)(void))jswrap_http_get, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  //{17, (void (*)(void))gen_jswrap_http_request, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))}
};
static const unsigned char jswSymbolIndex_http = 24;
static const JswSymPtr jswSymbols_Object_proto[] = {
  {0, (void (*)(void))jswrap_object_clone, JSWAT_JSVAR | JSWAT_THIS_ARG},
  {6, (void (*)(void))jswrap_object_emit, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*2))},
  {11, (void (*)(void))jswrap_object_hasOwnProperty, JSWAT_BOOL | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {26, (void (*)(void))jswrap_object_length, JSWAT_JSVAR | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY},
  {33, (void (*)(void))jswrap_object_on, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {36, (void (*)(void))jswrap_object_removeAllListeners, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {55, (void (*)(void))jswrap_object_toString, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {64, (void (*)(void))jswrap_object_valueOf, JSWAT_JSVAR | JSWAT_THIS_ARG}
};
static const unsigned char jswSymbolIndex_Object_proto = 25;
static const JswSymPtr jswSymbols_Nucleo[] = {
  /*{0, (void (*)(void))gen_jswrap_Nucleo_A0, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {3, (void (*)(void))gen_jswrap_Nucleo_A1, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {6, (void (*)(void))gen_jswrap_Nucleo_A2, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {9, (void (*)(void))gen_jswrap_Nucleo_A3, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {12, (void (*)(void))gen_jswrap_Nucleo_A4, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {15, (void (*)(void))gen_jswrap_Nucleo_A5, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {18, (void (*)(void))gen_jswrap_Nucleo_D0, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {21, (void (*)(void))gen_jswrap_Nucleo_D1, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {24, (void (*)(void))gen_jswrap_Nucleo_D10, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {28, (void (*)(void))gen_jswrap_Nucleo_D11, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {32, (void (*)(void))gen_jswrap_Nucleo_D12, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {36, (void (*)(void))gen_jswrap_Nucleo_D13, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {40, (void (*)(void))gen_jswrap_Nucleo_D14, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {44, (void (*)(void))gen_jswrap_Nucleo_D15, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {48, (void (*)(void))gen_jswrap_Nucleo_D2, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {51, (void (*)(void))gen_jswrap_Nucleo_D3, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {54, (void (*)(void))gen_jswrap_Nucleo_D4, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {57, (void (*)(void))gen_jswrap_Nucleo_D5, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {60, (void (*)(void))gen_jswrap_Nucleo_D6, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {63, (void (*)(void))gen_jswrap_Nucleo_D7, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {66, (void (*)(void))gen_jswrap_Nucleo_D8, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY},
  {69, (void (*)(void))gen_jswrap_Nucleo_D9, JSWAT_PIN | JSWAT_EXECUTE_IMMEDIATELY}*/
};
static const unsigned char jswSymbolIndex_Nucleo = 26;
static const JswSymPtr jswSymbols_Function_proto[] = {
  {0, (void (*)(void))jswrap_function_apply_or_call, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {6, (void (*)(void))jswrap_function_apply_or_call, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*2))},
  {11, (void (*)(void))jswrap_function_replaceWith, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_Function_proto = 27;
static const JswSymPtr jswSymbols_Socket_proto[] = {
  {0, (void (*)(void))jswrap_stream_available, JSWAT_INT32 | JSWAT_THIS_ARG},
  //{10, (void (*)(void))jswrap_net_socket_end, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {14, (void (*)(void))jswrap_pipe, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {19, (void (*)(void))jswrap_stream_read, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1))},
  //{24, (void (*)(void))jswrap_net_socket_write, JSWAT_BOOL | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_Socket_proto = 28;
static const JswSymPtr jswSymbols_httpSRq[] = {
  
};
static const unsigned char jswSymbolIndex_httpSRq = 29;
static const JswSymPtr jswSymbols_Date[] = {
  {0, (void (*)(void))jswrap_date_now, JSWAT_JSVARFLOAT},
  {4, (void (*)(void))jswrap_date_parse, JSWAT_JSVARFLOAT | (JSWAT_JSVAR << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_Date = 30;
static const JswSymPtr jswSymbols_httpCRs[] = {
  
};
static const unsigned char jswSymbolIndex_httpCRs = 31;
static const JswSymPtr jswSymbols_Pin_proto[] = {
  {0, (void (*)(void))jswrap_pin_read, JSWAT_BOOL | JSWAT_THIS_ARG},
  {5, (void (*)(void))jswrap_pin_reset, JSWAT_VOID | JSWAT_THIS_ARG},
  {11, (void (*)(void))jswrap_pin_set, JSWAT_VOID | JSWAT_THIS_ARG},
  {15, (void (*)(void))jswrap_pin_write, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_BOOL << (JSWAT_BITS*1))},
  {21, (void (*)(void))jswrap_pin_writeAtTime, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_BOOL << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2))}
};
static const unsigned char jswSymbolIndex_Pin_proto = 32;
static const JswSymPtr jswSymbols_Waveform_proto[] = {
  {0, (void (*)(void))jswrap_waveform_startInput, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_PIN << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {11, (void (*)(void))jswrap_waveform_startOutput, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_PIN << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {23, (void (*)(void))jswrap_waveform_stop, JSWAT_VOID | JSWAT_THIS_ARG}
};
static const unsigned char jswSymbolIndex_Waveform_proto = 33;
static const JswSymPtr jswSymbols_httpCRs_proto[] = {
  {0, (void (*)(void))jswrap_stream_available, JSWAT_INT32 | JSWAT_THIS_ARG},
  {10, (void (*)(void))jswrap_pipe, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {15, (void (*)(void))jswrap_stream_read, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_httpCRs_proto = 34;
static const JswSymPtr jswSymbols_httpSRs[] = {
  
};
static const unsigned char jswSymbolIndex_httpSRs = 35;
static const JswSymPtr jswSymbols_httpSrv_proto[] = {
  //{0, (void (*)(void))jswrap_net_server_close, JSWAT_VOID | JSWAT_THIS_ARG},
  //{6, (void (*)(void))jswrap_net_server_listen, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_httpSrv_proto = 36;
static const JswSymPtr jswSymbols_url[] = {
  //{0, (void (*)(void))jswrap_url_parse, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2))}
};
static const unsigned char jswSymbolIndex_url = 37;
static const JswSymPtr jswSymbols_SPI_proto[] = {
  {0, (void (*)(void))jswrap_spi_send, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_PIN << (JSWAT_BITS*2))},
  {5, (void (*)(void))jswrap_spi_send4bit, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)) | (JSWAT_PIN << (JSWAT_BITS*4))},
  {14, (void (*)(void))jswrap_spi_send8bit, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)) | (JSWAT_PIN << (JSWAT_BITS*4))},
  {23, (void (*)(void))jswrap_spi_setup, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {29, (void (*)(void))jswrap_spi_write, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_SPI_proto = 38;
static const JswSymPtr jswSymbols_String[] = {
  {0, (void (*)(void))jswrap_string_fromCharCode, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_String = 39;
static const JswSymPtr jswSymbols_SyntaxError_proto[] = {
  {0, (void (*)(void))jswrap_error_toString, JSWAT_JSVAR | JSWAT_THIS_ARG}
};
static const unsigned char jswSymbolIndex_SyntaxError_proto = 40;
static const JswSymPtr jswSymbols_net[] = {
  {0, (void (*)(void))gen_jswrap_net_connect, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  //{8, (void (*)(void))jswrap_net_createServer, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_net = 41;
static const JswSymPtr jswSymbols_ArrayBufferView_proto[] = {
  {0, (void (*)(void))gen_jswrap_ArrayBufferView_buffer, JSWAT_JSVAR | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY},
  {7, (void (*)(void))gen_jswrap_ArrayBufferView_byteLength, JSWAT_INT32 | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY},
  {18, (void (*)(void))gen_jswrap_ArrayBufferView_byteOffset, JSWAT_INT32 | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY},
  {29, (void (*)(void))jswrap_array_fill, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {34, (void (*)(void))jswrap_array_forEach, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {42, (void (*)(void))jswrap_array_indexOf, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {50, (void (*)(void))jswrap_array_join, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {55, (void (*)(void))jswrap_arraybufferview_map, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {59, (void (*)(void))jswrap_array_reduce, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {66, (void (*)(void))jswrap_array_reverse, JSWAT_JSVAR | JSWAT_THIS_ARG},
  {74, (void (*)(void))jswrap_arraybufferview_set, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2))},
  {78, (void (*)(void))jswrap_array_sort, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_ArrayBufferView_proto = 42;
static const JswSymPtr jswSymbols_Number_proto[] = {
  {0, (void (*)(void))jswrap_number_toFixed, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_Number_proto = 43;
static const JswSymPtr jswSymbols_httpSRq_proto[] = {
  {0, (void (*)(void))jswrap_stream_available, JSWAT_INT32 | JSWAT_THIS_ARG},
  {10, (void (*)(void))jswrap_pipe, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {15, (void (*)(void))jswrap_stream_read, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_httpSRq_proto = 44;
static const JswSymPtr jswSymbols_console[] = {
  {0, (void (*)(void))jswrap_interface_print, JSWAT_VOID | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_console = 45;
static const JswSymPtr jswSymbols_Array_proto[] = {
  {0, (void (*)(void))jswrap_array_concat, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))},
  {7, (void (*)(void))jswrap_array_every, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {13, (void (*)(void))jswrap_array_fill, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {18, (void (*)(void))jswrap_array_filter, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {25, (void (*)(void))jswrap_array_forEach, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {33, (void (*)(void))jswrap_array_indexOf, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {41, (void (*)(void))jswrap_array_join, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {46, (void (*)(void))jswrap_object_length, JSWAT_JSVAR | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY},
  {53, (void (*)(void))jswrap_array_map, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {57, (void (*)(void))gen_jswrap_Array_pop, JSWAT_JSVAR | JSWAT_THIS_ARG},
  {61, (void (*)(void))jswrap_array_push, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))},
  {66, (void (*)(void))jswrap_array_reduce, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {73, (void (*)(void))jswrap_array_reverse, JSWAT_JSVAR | JSWAT_THIS_ARG},
  {81, (void (*)(void))jswrap_array_shift, JSWAT_JSVAR | JSWAT_THIS_ARG},
  {87, (void (*)(void))jswrap_array_slice, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {93, (void (*)(void))jswrap_array_some, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2))},
  {98, (void (*)(void))jswrap_array_sort, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {103, (void (*)(void))jswrap_array_splice, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*3))},
  {110, (void (*)(void))jswrap_object_toString, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  {119, (void (*)(void))jswrap_array_unshift, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_Array_proto = 46;
static const JswSymPtr jswSymbols_httpCRq_proto[] = {
  //{0, (void (*)(void))jswrap_net_socket_end, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))},
  //{4, (void (*)(void))jswrap_net_socket_write, JSWAT_BOOL | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))}
};
static const unsigned char jswSymbolIndex_httpCRq_proto = 47;
static const JswSymPtr jswSymbols_process[] = {
  {0, (void (*)(void))jswrap_process_env, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY},
  {4, (void (*)(void))jswrap_process_memory, JSWAT_JSVAR},
  {11, (void (*)(void))gen_jswrap_process_version, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY}
};
static const unsigned char jswSymbolIndex_process = 48;
static const JswSymPtr jswSymbols_WLAN_proto[] = {
  /*
  {0, (void (*)(void))jswrap_wlan_connect, JSWAT_BOOL | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3))},
  {8, (void (*)(void))jswrap_wlan_disconnect, JSWAT_VOID | JSWAT_THIS_ARG},
  {19, (void (*)(void))jswrap_wlan_getIP, JSWAT_JSVAR | JSWAT_THIS_ARG},
  {25, (void (*)(void))jswrap_wlan_reconnect, JSWAT_VOID | JSWAT_THIS_ARG},
  {35, (void (*)(void))jswrap_wlan_setIP, JSWAT_BOOL | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1))}
	*/
};
static const unsigned char jswSymbolIndex_WLAN_proto = 49;


const JswSymList jswSymbolTables[] = {
  {jswSymbols_I2C_proto, 3, "readFrom\0setup\0writeTo\0"},
  {jswSymbols_Date_proto, 13, "getDate\0getDay\0getFullYear\0getHours\0getMilliseconds\0getMinutes\0getMonth\0getSeconds\0getTime\0getTimezoneOffset\0toString\0toUTCString\0valueOf\0"},
  {jswSymbols_Graphics, 2, "createArrayBuffer\0createCallback\0"},
  {jswSymbols_E, 18, "FFT\0clip\0convolve\0dumpTimers\0enableWatchdog\0getAnalogVRef\0getErrorFlags\0getSizeOf\0getTemperature\0interpolate\0interpolate2d\0nativeCall\0reverseByte\0sum\0toArrayBuffer\0toString\0toUint8Array\0variance\0"},
  {jswSymbols_Server_proto, 2, "close\0listen\0"},
  {jswSymbols_Socket, 0, ""},
  {jswSymbols_String_proto, 12, "charAt\0charCodeAt\0indexOf\0lastIndexOf\0length\0replace\0slice\0split\0substr\0substring\0toLowerCase\0toUpperCase\0"},
  {jswSymbols_OneWire_proto, 7, "read\0reset\0search\0search\0select\0skip\0write\0"},
  {jswSymbols_Serial, 0, ""},
  {jswSymbols_httpSRs_proto, 3, "end\0write\0writeHead\0"},
  {jswSymbols_JSON, 2, "parse\0stringify\0"},
  {jswSymbols_global, 103, "Array\0ArrayBuffer\0ArrayBufferView\0Boolean\0Date\0E\0Error\0Float32Array\0Float64Array\0Function\0Graphics\0HIGH\0Hardware\0I2C\0I2C1\0I2C2\0I2C3\0Infinity\0Int16Array\0Int32Array\0Int8Array\0InternalError\0JSON\0LOW\0LoopbackA\0LoopbackB\0Math\0Modules\0NaN\0Nucleo\0Number\0Object\0OneWire\0Pin\0SPI\0SPI1\0SPI2\0SPI3\0Serial\0Serial1\0Serial2\0Serial3\0Server\0Socket\0String\0SyntaxError\0Uint16Array\0Uint32Array\0Uint8Array\0Uint8ClampedArray\0WLAN\0Waveform\0analogRead\0analogWrite\0arguments\0atob\0btoa\0changeInterval\0clearInterval\0clearTimeout\0clearWatch\0console\0digitalPulse\0digitalRead\0digitalWrite\0dump\0echo\0edit\0eval\0fs\0getPinMode\0getSerial\0getTime\0httpCRq\0httpCRs\0httpSRq\0httpSRs\0httpSrv\0isNaN\0load\0parseFloat\0parseInt\0peek16\0peek32\0peek8\0pinMode\0poke16\0poke32\0poke8\0print\0process\0require\0reset\0save\0setBusyIndicator\0setDeepSleep\0setInterval\0setSleepIndicator\0setTime\0setTimeout\0setWatch\0trace\0url\0"},
  {jswSymbols_Modules, 4, "addCached\0getCached\0removeAllCached\0removeCached\0"},
  {jswSymbols_Error_proto, 1, "toString\0"},
  {jswSymbols_Object, 4, "create\0getOwnPropertyDescriptor\0getOwnPropertyNames\0keys\0"},
  {jswSymbols_httpCRq, 0, ""},
  {jswSymbols_Serial_proto, 9, "available\0onData\0pipe\0print\0println\0read\0setConsole\0setup\0write\0"},
  {jswSymbols_CC3000, 1, "connect\0"},
  {jswSymbols_Array, 1, "isArray\0"},
  {jswSymbols_Number, 5, "MAX_VALUE\0MIN_VALUE\0NEGATIVE_INFINITY\0NaN\0POSITIVE_INFINITY\0"},
  {jswSymbols_Math, 28, "E\0LN10\0LN2\0LOG10E\0LOG2E\0PI\0SQRT1_2\0SQRT2\0abs\0acos\0asin\0atan\0atan2\0ceil\0clip\0cos\0exp\0floor\0log\0max\0min\0pow\0random\0round\0sin\0sqrt\0tan\0wrap\0"},
  {jswSymbols_Graphics_proto, 24, "clear\0drawImage\0drawLine\0drawRect\0drawString\0fillPoly\0fillRect\0getBgColor\0getColor\0getHeight\0getPixel\0getWidth\0lineTo\0moveTo\0setBgColor\0setBgColorHSV\0setColor\0setColorHSV\0setFontBitmap\0setFontCustom\0setFontVector\0setPixel\0setRotation\0stringWidth\0"},
  {jswSymbols_fs, 1, "pipe\0"},
  {jswSymbols_InternalError_proto, 1, "toString\0"},
  {jswSymbols_http, 3, "createServer\0get\0request\0"},
  {jswSymbols_Object_proto, 8, "clone\0emit\0hasOwnProperty\0length\0on\0removeAllListeners\0toString\0valueOf\0"},
  {jswSymbols_Nucleo, 22, "A0\0A1\0A2\0A3\0A4\0A5\0D0\0D1\0D10\0D11\0D12\0D13\0D14\0D15\0D2\0D3\0D4\0D5\0D6\0D7\0D8\0D9\0"},
  {jswSymbols_Function_proto, 3, "apply\0call\0replaceWith\0"},
  {jswSymbols_Socket_proto, 5, "available\0end\0pipe\0read\0write\0"},
  {jswSymbols_httpSRq, 0, ""},
  {jswSymbols_Date, 2, "now\0parse\0"},
  {jswSymbols_httpCRs, 0, ""},
  {jswSymbols_Pin_proto, 5, "read\0reset\0set\0write\0writeAtTime\0"},
  {jswSymbols_Waveform_proto, 3, "startInput\0startOutput\0stop\0"},
  {jswSymbols_httpCRs_proto, 3, "available\0pipe\0read\0"},
  {jswSymbols_httpSRs, 0, ""},
  {jswSymbols_httpSrv_proto, 2, "close\0listen\0"},
  {jswSymbols_url, 1, "parse\0"},
  {jswSymbols_SPI_proto, 5, "send\0send4bit\0send8bit\0setup\0write\0"},
  {jswSymbols_String, 1, "fromCharCode\0"},
  {jswSymbols_SyntaxError_proto, 1, "toString\0"},
  {jswSymbols_net, 2, "connect\0createServer\0"},
  {jswSymbols_ArrayBufferView_proto, 12, "buffer\0byteLength\0byteOffset\0fill\0forEach\0indexOf\0join\0map\0reduce\0reverse\0set\0sort\0"},
  {jswSymbols_Number_proto, 1, "toFixed\0"},
  {jswSymbols_httpSRq_proto, 3, "available\0pipe\0read\0"},
  {jswSymbols_console, 1, "log\0"},
  {jswSymbols_Array_proto, 20, "concat\0every\0fill\0filter\0forEach\0indexOf\0join\0length\0map\0pop\0push\0reduce\0reverse\0shift\0slice\0some\0sort\0splice\0toString\0unshift\0"},
  {jswSymbols_httpCRq_proto, 2, "end\0write\0"},
  {jswSymbols_process, 3, "env\0memory\0version\0"},
  {jswSymbols_WLAN_proto, 5, "connect\0disconnect\0getIP\0reconnect\0setIP\0"},
};


JsVar *jswFindBuiltInFunction(JsVar *parent, const char *name) {
  JsVar *v;
  if (parent && !jsvIsRoot(parent)) {
    // ------------------------------------------ INSTANCE + STATIC METHODS
    if (jsvIsNativeFunction(parent)) {
      if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_Graphics_Graphics) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Graphics], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_E_E) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_E], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_Socket_Socket) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Socket], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_Serial_Serial) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Serial], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_JSON_JSON) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_JSON], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_Modules_Modules) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Modules], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_Object_Object) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Object], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_httpCRq_httpCRq) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_httpCRq], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_CC3000_CC3000) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_CC3000], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)jswrap_array_constructor) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Array], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)jswrap_number_constructor) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Number], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_Math_Math) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Math], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_fs_fs) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_fs], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_http_http) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_http], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_Nucleo_Nucleo) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Nucleo], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_httpSRq_httpSRq) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_httpSRq], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)jswrap_date_constructor) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Date], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_httpCRs_httpCRs) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_httpCRs], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_httpSRs_httpSRs) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_httpSRs], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_url_url) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_url], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)jswrap_string_constructor) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_String], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_net_net) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_net], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_console_console) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_console], parent, name);
        if (v) return v;
      } else if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_process_process) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_process], parent, name);
        if (v) return v;
      }
    }
    if (jsvIsString(parent)) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_String_proto], parent, name);
      if (v) return v;
    }
    if (jsvIsFunction(parent)) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Function_proto], parent, name);
      if (v) return v;
    }
    if (jsvIsPin(parent)) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Pin_proto], parent, name);
      if (v) return v;
    }
    if (jsvIsArrayBuffer(parent) && parent->varData.arraybuffer.type!=ARRAYBUFFERVIEW_ARRAYBUFFER) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_ArrayBufferView_proto], parent, name);
      if (v) return v;
    }
    if (jsvIsInt(parent) || jsvIsFloat(parent)) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Number_proto], parent, name);
      if (v) return v;
    }
    if (jsvIsArray(parent)) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Array_proto], parent, name);
      if (v) return v;
    }
    // ------------------------------------------ INSTANCE METHODS WE MUST CHECK CONSTRUCTOR FOR
    JsVar *proto = jsvIsObject(parent)?jsvSkipNameAndUnLock(jsvFindChildFromString(parent, JSPARSE_INHERITS_VAR, false)):0;
    JsVar *constructor = jsvIsObject(proto)?jsvSkipNameAndUnLock(jsvFindChildFromString(proto, JSPARSE_CONSTRUCTOR_VAR, false)):0;
    jsvUnLock(proto);
    if (constructor && jsvIsNativeFunction(constructor)) {
      void *constructorPtr = constructor->varData.native.ptr;
      jsvUnLock(constructor);
      if (constructorPtr==(void*)gen_jswrap_I2C_I2C) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_I2C_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)jswrap_date_constructor) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Date_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)gen_jswrap_Server_Server) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Server_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)jswrap_onewire_constructor) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_OneWire_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)gen_jswrap_httpSRs_httpSRs) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_httpSRs_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)jswrap_error_constructor) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Error_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)gen_jswrap_Serial_Serial) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Serial_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)gen_jswrap_Graphics_Graphics) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Graphics_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)jswrap_internalerror_constructor) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_InternalError_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)gen_jswrap_Socket_Socket) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Socket_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)jswrap_waveform_constructor) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Waveform_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)gen_jswrap_httpCRs_httpCRs) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_httpCRs_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)gen_jswrap_httpSrv_httpSrv) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_httpSrv_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)jswrap_spi_constructor) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_SPI_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)jswrap_syntaxerror_constructor) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_SyntaxError_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)gen_jswrap_httpSRq_httpSRq) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_httpSRq_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)gen_jswrap_httpCRq_httpCRq) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_httpCRq_proto], parent, name);
        if (v) return v;
      } else if (constructorPtr==(void*)gen_jswrap_WLAN_WLAN) {
        v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_WLAN_proto], parent, name);
        if (v) return v;
      }
    } else {
      jsvUnLock(constructor);
    }
    // ------------------------------------------ METHODS ON OBJECT
    v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Object_proto], parent, name);
    if (v) return v;
  } else { /* if (!parent) */
    // ------------------------------------------ FUNCTIONS
    // Handle pin names - eg LED1 or D5 (this is hardcoded in build_jsfunctions.py)
    Pin pin = jshGetPinFromString(name);
    if (pin != NC) {
      return jsvNewFromPin(pin);
    }
    return jswBinarySearch(&jswSymbolTables[jswSymbolIndex_global], parent, name);
  }
  return 0;
}


const JswSymList *jswGetSymbolListForObject(JsVar *parent) {
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_Graphics_Graphics) return &jswSymbolTables[jswSymbolIndex_Graphics];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_E_E) return &jswSymbolTables[jswSymbolIndex_E];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_Socket_Socket) return &jswSymbolTables[jswSymbolIndex_Socket];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_Serial_Serial) return &jswSymbolTables[jswSymbolIndex_Serial];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_JSON_JSON) return &jswSymbolTables[jswSymbolIndex_JSON];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_Modules_Modules) return &jswSymbolTables[jswSymbolIndex_Modules];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_Object_Object) return &jswSymbolTables[jswSymbolIndex_Object];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_httpCRq_httpCRq) return &jswSymbolTables[jswSymbolIndex_httpCRq];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_CC3000_CC3000) return &jswSymbolTables[jswSymbolIndex_CC3000];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)jswrap_array_constructor) return &jswSymbolTables[jswSymbolIndex_Array];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)jswrap_number_constructor) return &jswSymbolTables[jswSymbolIndex_Number];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_Math_Math) return &jswSymbolTables[jswSymbolIndex_Math];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_fs_fs) return &jswSymbolTables[jswSymbolIndex_fs];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_http_http) return &jswSymbolTables[jswSymbolIndex_http];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_Nucleo_Nucleo) return &jswSymbolTables[jswSymbolIndex_Nucleo];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_httpSRq_httpSRq) return &jswSymbolTables[jswSymbolIndex_httpSRq];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)jswrap_date_constructor) return &jswSymbolTables[jswSymbolIndex_Date];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_httpCRs_httpCRs) return &jswSymbolTables[jswSymbolIndex_httpCRs];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_httpSRs_httpSRs) return &jswSymbolTables[jswSymbolIndex_httpSRs];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_url_url) return &jswSymbolTables[jswSymbolIndex_url];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)jswrap_string_constructor) return &jswSymbolTables[jswSymbolIndex_String];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_net_net) return &jswSymbolTables[jswSymbolIndex_net];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_console_console) return &jswSymbolTables[jswSymbolIndex_console];
  if (jsvIsNativeFunction(parent) && (void*)parent->varData.native.ptr==(void*)gen_jswrap_process_process) return &jswSymbolTables[jswSymbolIndex_process];
  return 0;
}


const JswSymList *jswGetSymbolListForObjectProto(JsVar *parent) {
  if (jsvIsNativeFunction(parent)) {
    if ((void*)parent->varData.native.ptr==(void*)jswrap_string_constructor) return &jswSymbolTables[jswSymbolIndex_String_proto];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_function_constructor) return &jswSymbolTables[jswSymbolIndex_Function_proto];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_pin_constructor) return &jswSymbolTables[jswSymbolIndex_Pin_proto];
    if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_ArrayBufferView_ArrayBufferView) return &jswSymbolTables[jswSymbolIndex_ArrayBufferView_proto];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_number_constructor) return &jswSymbolTables[jswSymbolIndex_Number_proto];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_array_constructor) return &jswSymbolTables[jswSymbolIndex_Array_proto];
  }
  JsVar *constructor = jsvIsObject(parent)?jsvSkipNameAndUnLock(jsvFindChildFromString(parent, JSPARSE_CONSTRUCTOR_VAR, false)):0;
  if (constructor && jsvIsNativeFunction(constructor)) {
    void *constructorPtr = constructor->varData.native.ptr;
   jsvUnLock(constructor);
    if (constructorPtr==(void*)gen_jswrap_I2C_I2C) return &jswSymbolTables[jswSymbolIndex_I2C_proto];
    if (constructorPtr==(void*)jswrap_date_constructor) return &jswSymbolTables[jswSymbolIndex_Date_proto];
    if (constructorPtr==(void*)gen_jswrap_Server_Server) return &jswSymbolTables[jswSymbolIndex_Server_proto];
    if (constructorPtr==(void*)jswrap_onewire_constructor) return &jswSymbolTables[jswSymbolIndex_OneWire_proto];
    if (constructorPtr==(void*)gen_jswrap_httpSRs_httpSRs) return &jswSymbolTables[jswSymbolIndex_httpSRs_proto];
    if (constructorPtr==(void*)jswrap_error_constructor) return &jswSymbolTables[jswSymbolIndex_Error_proto];
    if (constructorPtr==(void*)gen_jswrap_Serial_Serial) return &jswSymbolTables[jswSymbolIndex_Serial_proto];
    if (constructorPtr==(void*)gen_jswrap_Graphics_Graphics) return &jswSymbolTables[jswSymbolIndex_Graphics_proto];
    if (constructorPtr==(void*)jswrap_internalerror_constructor) return &jswSymbolTables[jswSymbolIndex_InternalError_proto];
    if (constructorPtr==(void*)gen_jswrap_Socket_Socket) return &jswSymbolTables[jswSymbolIndex_Socket_proto];
    if (constructorPtr==(void*)jswrap_waveform_constructor) return &jswSymbolTables[jswSymbolIndex_Waveform_proto];
    if (constructorPtr==(void*)gen_jswrap_httpCRs_httpCRs) return &jswSymbolTables[jswSymbolIndex_httpCRs_proto];
    if (constructorPtr==(void*)gen_jswrap_httpSrv_httpSrv) return &jswSymbolTables[jswSymbolIndex_httpSrv_proto];
    if (constructorPtr==(void*)jswrap_spi_constructor) return &jswSymbolTables[jswSymbolIndex_SPI_proto];
    if (constructorPtr==(void*)jswrap_syntaxerror_constructor) return &jswSymbolTables[jswSymbolIndex_SyntaxError_proto];
    if (constructorPtr==(void*)gen_jswrap_httpSRq_httpSRq) return &jswSymbolTables[jswSymbolIndex_httpSRq_proto];
    if (constructorPtr==(void*)gen_jswrap_httpCRq_httpCRq) return &jswSymbolTables[jswSymbolIndex_httpCRq_proto];
    if (constructorPtr==(void*)gen_jswrap_WLAN_WLAN) return &jswSymbolTables[jswSymbolIndex_WLAN_proto];
  }
  return &jswSymbolTables[jswSymbolIndex_Object_proto];
}


bool jswIsBuiltInObject(const char *name) {
  return
strcmp(name, "Array")==0 ||
    strcmp(name, "ArrayBuffer")==0 ||
    strcmp(name, "ArrayBufferView")==0 ||
    strcmp(name, "Uint8Array")==0 ||
    strcmp(name, "Uint8ClampedArray")==0 ||
    strcmp(name, "Int8Array")==0 ||
    strcmp(name, "Uint16Array")==0 ||
    strcmp(name, "Int16Array")==0 ||
    strcmp(name, "Uint32Array")==0 ||
    strcmp(name, "Int32Array")==0 ||
    strcmp(name, "Float32Array")==0 ||
    strcmp(name, "Float64Array")==0 ||
    strcmp(name, "Date")==0 ||
    strcmp(name, "Error")==0 ||
    strcmp(name, "SyntaxError")==0 ||
    strcmp(name, "InternalError")==0 ||
    strcmp(name, "E")==0 ||
    strcmp(name, "Function")==0 ||
    strcmp(name, "console")==0 ||
    strcmp(name, "JSON")==0 ||
    strcmp(name, "Modules")==0 ||
    strcmp(name, "Number")==0 ||
    strcmp(name, "Hardware")==0 ||
    strcmp(name, "Object")==0 ||
    strcmp(name, "Boolean")==0 ||
    strcmp(name, "OneWire")==0 ||
    strcmp(name, "Pin")==0 ||
    strcmp(name, "fs")==0 ||
    strcmp(name, "process")==0 ||
    strcmp(name, "Serial")==0 ||
    strcmp(name, "SPI")==0 ||
    strcmp(name, "I2C")==0 ||
    strcmp(name, "String")==0 ||
    strcmp(name, "Waveform")==0 ||
    strcmp(name, "Math")==0 ||
    strcmp(name, "Graphics")==0 ||
    strcmp(name, "url")==0 ||
    strcmp(name, "Server")==0 ||
    strcmp(name, "Socket")==0 ||
    strcmp(name, "httpSrv")==0 ||
    strcmp(name, "httpSRq")==0 ||
    strcmp(name, "httpSRs")==0 ||
    strcmp(name, "httpCRq")==0 ||
    strcmp(name, "httpCRs")==0 ||
    strcmp(name, "WLAN")==0 ||
    strcmp(name, "Nucleo")==0;
}


void *jswGetBuiltInLibrary(const char *name) {
if (strcmp(name, "Pipe")==0) return (void*)gen_jswrap_Pipe_Pipe;
if (strcmp(name, "net")==0) return (void*)gen_jswrap_net_net;
if (strcmp(name, "http")==0) return (void*)gen_jswrap_http_http;
if (strcmp(name, "CC3000")==0) return (void*)gen_jswrap_CC3000_CC3000;
  return 0;
}


/** Given a variable, return the basic object name of it */
const char *jswGetBasicObjectName(JsVar *var) {
  if (jsvIsFunction(var)) return "Function";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_INT32) return "Int32Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==(ARRAYBUFFERVIEW_UINT8|ARRAYBUFFERVIEW_CLAMPED)) return "Uint8ClampedArray";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_UINT32) return "Uint32Array";
  if (jsvIsPin(var)) return "Pin";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_ARRAYBUFFER) return "ArrayBuffer";
  if (jsvIsObject(var)) return "Object";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_UINT8) return "Uint8Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_UINT16) return "Uint16Array";
  if (jsvIsRoot(var)) return "Hardware";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_FLOAT64) return "Float64Array";
  if (jsvIsNumeric(var)) return "Number";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_INT8) return "Int8Array";
  if (jsvIsArray(var)) return "Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_INT16) return "Int16Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_FLOAT32) return "Float32Array";
  if (jsvIsString(var)) return "String";
  return 0;
}


/** Given the name of a Basic Object, eg, Uint8Array, String, etc. Return the prototype object's name - or 0. */
const char *jswGetBasicObjectPrototypeName(const char *objectName) {
  if (!strcmp(objectName, "Uint8Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Uint8ClampedArray")) return "ArrayBufferView";
  if (!strcmp(objectName, "Int8Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Uint16Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Int16Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Uint32Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Int32Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Float32Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Float64Array")) return "ArrayBufferView";
  return strcmp(objectName,"Object") ? "Object" : 0;
}


/** Tasks to run on Idle. Returns true if either one of the tasks returned true (eg. they're doing something and want to avoid sleeping) */
bool jswIdle() {
  bool wasBusy = false;
  if (jswrap_pipe_idle()) wasBusy = true;
  if (jswrap_waveform_idle()) wasBusy = true;
  //if (jswrap_graphics_idle()) wasBusy = true;
  //if (jswrap_net_idle()) wasBusy = true;
  return wasBusy;
}


/** Tasks to run on Initialisation */
void jswInit() {
  //jswrap_graphics_init();
  //jswrap_net_init();
}


/** Tasks to run on Deinitialisation */
void jswKill() {
  jswrap_pipe_kill();
  jswrap_waveform_kill();
  //jswrap_net_kill();
}


